exercise/highcharts-maps-1
blacklabel/highcharts-fundamentals-kamil-musialowski pull request #17
Opened 2022-07-07 10:43 UTC by kamil-musialowski

2022-08-16 11:17 UTC, pawellysy requested changes
Why in this pr are some changes from stock exercise?

2022-08-16 11:17 UTC, pawellysy commented on highcharts-api/highcharts-stock/1-live-data-tools/main.js
> +let liveData = [];
Why in this pr are some changes from the stock exercise?

2022-08-18 16:37 UTC, magdalena-gut requested changes

2022-08-18 16:37 UTC, magdalena-gut commented on highcharts-api/highcharts-maps/1-points-joinby/main.js
> +        ],
Unnecessary comma ;)

2022-09-05 14:22 UTC, kamil-musialowski commented on highcharts-api/highcharts-stock/1-live-data-tools/main.js
> +let liveData = [];
Used `git reset HEAD~2` to remove last two commits, then `git push --force` with correct files.

2022-09-05 19:48 UTC, magdalena-gut approved these changes
LGTM!

2025-01-14 15:17 UTC, closed without merging