exercise/highcharts-7
blacklabel/highcharts-fundamentals-kamil-musialowski pull request #7
Opened 2022-05-22 07:34 UTC by kamil-musialowski

2022-08-10 09:00 UTC, K009 requested changes

2022-08-10 09:00 UTC, K009 commented on highcharts-api/highcharts/7-connecting-column-edges/main.js
> +        .add();
Addin' an SVG element to a series group would be more appropriate here. 3 reasons why:

- connected lines will become animated
- no need to add _plotLeft_ / _plotTop_ to _x_ and _y_ values
- shortens lines 34-37, so they don't have to be break 

The line would look like: `.add(series.group)`

2022-08-30 16:56 UTC, K009 commented on highcharts-api/highcharts/7-connecting-column-edges/main.js
> +        .add();
I wouldn't say so. Remember that we're not adding all the lines to the first series group (as you wrote: `chart.series[0].group.` Each color has its own series it should be assigned to. Please check if I'm right with that 😄

2022-08-30 16:57 UTC, K009 requested changes
Waiting for the resolution of the above discussion.

2022-08-31 07:20 UTC, kamil-musialowski commented on highcharts-api/highcharts/7-connecting-column-edges/main.js
> +        .add();
I get it now! I have implemented it in the latest commit.

2025-01-14 15:18 UTC, closed without merging